class Account{ //Creating Account class to encapsulate and organize database interactions) 
    constructor(account_id, username, password, role){
        
        //An id will be automatically generated by the database
        this.account_id = account_id;
        //username for this account (must be unique and not blank)
        this.username = username;
        //password for this account (must be over 8 characters)
        this.password = password;
        //
        this.role = role;
       // Will model with Class transformer
    }

    /*
Reimbursement info:
-Amount
-Description
-Status
-Employee ID 
 */

}

class Request{ //Creating Account class to encapsulate and organize database interactions) 
    constructor( request_number, amount, description, status, account_id){
        
        //An request number will be automatically generated by the database
        this.request_number = request_number;
        //amount for this request (number)
        this.amount = amount;
        //description for this account (string)
        this.description = description;
        //status (string - limited approved, denied , pending - update on change)
        this.status = status;
        // account id must match requester 
        this.account_id = account_id;
       // Will model with Class-transformer
    }

}




